name: Lambda GitHub App webhook
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - .github/workflows/lambda.yml
      - "examples/lambda-nodejs-ts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:12
    defaults:
      run:
        working-directory: examples/lambda-nodejs-ts

    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Run linter
        run: yarn lint
      - name: Build distribution
        run: yarn build
